site_name: b3-exmo's notes

theme:
  name: material
  icon:
    logo: material/bee
  favicon: img/bee-icon.png
  custom_dir: overrides
  palette:
  # Light mode
  - media: '(prefers-color-scheme: light)'
    scheme: default
    primary: custom
    accent: custom
    toggle:
      icon: material/brightness-4
      name: Switch to dark mode
  # Dark mode
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    primary: custom
    accent: custom
    toggle:
      icon: material/brightness-7
      name: Switch to light mode
  font:
    text: Inter
    code: Fira Code

  features:
  - navigation.indexes
  - navigation.instant
  - navigation.instant.progress
  - navigation.path
  - navigation.top
  - navigation.tracking
  - toc.follow

# Extensions
markdown_extensions:
  - footnotes
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.details
  - pymdownx.tilde:
      subscript: true

  - toc:
      permalink: true

plugins:
  - search
  - roamlinks
  - open-in-new-tab
  - mkdocs-video
  - section-index
  - timetoread:
      wpm: 225

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - js/jquery-3.7.1.min.js
  - js/favicon.js

nav:
  - ⛪ Home: index.md
  - ✍️ My own experience: My own experience.md
  - ✝️ Christianity:
    - 😈 Satan: Christianity/Satan.md
    - 👹 Satan's Origins: Christianity/Satan-origins.md
    - 😱 Satanic Panic: Christianity/Satanic-panic.md
    - 🥈 Second Coming: Christianity/Second Coming.md
    - 🌩 Theology: Christianity/Theology.md
    - ❓ What are blessings?: Christianity/What are blessings.md
  - 💬 Commentated Documents:
    - 💒 D&C 132: Commentated Docs/DC 132.md
    - 🤔 Doubts and Truth: Commentated Docs/Doubts and Truth.md
    - 🏎 Essay - Race & Priesthood: Commentated Docs/Essay Race Priesthood.md
    - 🤡 Fourteen Fundamentals in Following the Prophet: Commentated Docs/14 Fundamentals.md
    - "😵 Quotes: It's too sacred!": Commentated Docs/quotes-too-sacred.md
    - 💭 What Do We Mean When We Say the Church Is True?: Commentated Docs/What Do We Mean When We Say the Church Is True.md
  - 🤨 Critical Thinking:
    - Critical thinking/Critical Thinking.md
    - 🧠 Cognitive Bias: Critical thinking/Cognitive Bias.md
    - 🥺 Emotional Thinking: Critical thinking/Emotional Thinking.md
    - 👎 Falsifiability: Critical thinking/Falsifiability.md
    - 😳 Impossible Gospel: Critical thinking/impossible-gospel.md
    - ♟️ Logical Fallacies: Critical thinking/logical-fallacies.md
    - 🧪 Shelf: Critical thinking/Shelf.md
  - 👥 Culture:
    # - Culture/Culture.md
    - 😬 Anxiety: Culture/Anxiety.md
    - 🥓 Curated Information: Culture/Curated Sources.md
    - 😨 Don't leave!: Culture/Dont-leave.md
    - 💔 God's Conditional Love: Culture/Gods Conditional Love.md
    - 🤕 Imperfect Leaders: Culture/Perfection/imperfect-leaders.md
    - ☝️🤓 Name "Mormon": Culture/Name Mormon.md
    - 👑 Privilege: Culture/Privilege.md
    - ✔️ Scrupulosity: Culture/Scrupulosity.md
    - ⚧️ Sexuality & Repression: Culture/Sexuality Repression.md
    - 💪 Strengthening Church Members Committee: Culture/Strengthening Church Members Committee.md
    - 😔 Too Sacred to Share: Culture/Too Sacred to Share.md
    - ✅ True: Culture/True.md
  - 📐 Doctrine:
    - Doctrines/Doctrine.md
    - 🪦 Afterlife: Doctrines/Afterlife.md
    - 🌊 Baptism: Doctrines/Baptism.md
    - 🪄 Becoming Gods: Doctrines/Becoming Gods.md
    - 🧭 Course Correction: Doctrines/course-correction.md
    - 🩲 Garments: Doctrines/Garments.md
    - 👩‍🤝‍👩 Polygamy: 
      - Doctrines/Polygamy/Polygamy.md
      # - 🛏 Consummation: Doctrines/Polygamy/Consummation.md
      - 👧 Helen Mar Kimball: Doctrines/Polygamy/Helen Kimball.md
      - 🥩💱 Meat Commerce: Doctrines/Polygamy/Meat commerce.md
      - 😏 Sealing: Doctrines/Polygamy/Sealing.md
    - 🍻 Word of Wisdom: 
      - Doctrines/Word of Wisdom/Word-of-Wisdom.md
      - ☕ CAFFEINE: Doctrines/Word of Wisdom/CAFFEINE.md
      - "🍂 Word of Wisdom: Changes": Doctrines/Word of Wisdom/WoW Changes.md
      - "💬 Word of Wisdom: Interpretations": Doctrines/Word of Wisdom/WoW Interpretations.md
  - 🏳‍🌈 LGBTQ+: LGBT/LGBTQ.md
  - 🔮 Modern Church:
    - 🧔 Jesus and The Church: Modern Church/Jesus-and-The-Church.md
    - 📜 LDS Historians: Modern Church/Historians.md
    - 🧍‍♂️ No Official Stance: Modern Church/No-official-stance.md
    - 🧼 Whitewashing History: Modern Church/Whitewashing.md
  - 👨‍💼 Prophets:
    - Prophets/Prophets.md
    - 🌱 Restoration: Prophets/Restoration.md
    - 😤 Brigham Young:
      - Prophets/Brigham Young/Brigham Young.md
      - 🩸 Blood Atonement: Prophets/Brigham Young/Blood Atonement.md
      - 🥊 Vs. Emma Smith: Prophets/Brigham Young/Vs Emma Smith.md
    - 🌳 Dallin H. Oaks: Prophets/Dallin Oaks/Dallin-Oaks.md
    - 🇺🇸 Ezra Taft Benson: Prophets/Ezra Taft Benson/Ezra Taft Benson.md
    - 😍 Joseph Smith: 
      - Prophets/Joseph Smith/Joseph Smith.md
      - 😏 Boasting: Prophets/Joseph Smith/Boasting.md
      - 🎓 Education: Prophets/Joseph Smith/Education.md
      - 🕶 First Vision:
        - 🕶 First Vision: Prophets/Joseph Smith/First Vision/First Vision.md
        - 🙈 Concealment: Prophets/Joseph Smith/First Vision/First Vision Concealment.md
        - 🤼 Contemporaries: Prophets/Joseph Smith/First Vision/First Vision Contemporaries.md
        - 🚩 Problems: Prophets/Joseph Smith/First Vision/First Vision Problems.md
        - ⚖️ Similar Experiences: Prophets/Joseph Smith/First Vision/First Vision Similar Experiences.md
      - 🎣 Kinderhook Plates: Prophets/Joseph Smith/Kinderhook Plates.md
    - 👴 Russel M Nelson:
      - 👴 Russell M Nelson: Prophets/Russell-Nelson/Russell-M-Nelson.md
      - 🛩 Nelson's Plane: Prophets/Russell-Nelson/Nelsons-Plane.md
      - 😷 Nelson vs. COVID: Prophets/Russell-Nelson/Nelson-vs-Covid.md
      - 🏃‍➡️ Social Media Fasting: Prophets/Russell-Nelson/Nelson-social-media-fast.md
  - 🏁 Race: 
    - Race/Race.md
    - 🤼 Race in Scripture: Race/Race in scripture.md
    - 🎩 "Skin of Blackness": Race/Skin of blackness.md
    - 🌶 Various Quotes: Race/Various Quotes.md
  - 📚 Scripture: 
    - 📑 Bible: Scripture/Bible.md
    - 📘 Book of Mormon:
      - Scripture/Book of Mormon/Book of Mormon.md
      - 😔 After all we can do: Scripture/Book of Mormon/After all we can do.md
      - 📪 Cannot be Written: Scripture/Book of Mormon/cannot-be-written.md
      - 🔃 Changes: Scripture/Book of Mormon/Changes.md
      # - 🤷 Isaiah: Scripture/Book of Mormon/Isaiah.md
      - ⚔️ Jaredites: Scripture/Book of Mormon/Jaredites.md
      - 🙅‍♂️ Korihor: Scripture/Book of Mormon/Korihor.md
      - 😴 Lehi's Dream: Scripture/Book of Mormon/Lehi-dream.md
      - 📚 Literary Value: Scripture/Book of Mormon/Literary Value.md
      - ❓ Logistial Problems: Scripture/Book of Mormon/logistical-problems.md
      - ♀️ Representation of Women: Scripture/Book of Mormon/Representation of Women.md
      - ⚓ Seafaring: Scripture/Book of Mormon/Seafaring.md
      - 🤖 Technology: Scripture/Book of Mormon/Technology.md
      - 🍽 The Plates: Scripture/Book of Mormon/The Plates.md
      - 👅 Translation: Scripture/Book of Mormon/Translation.md
    - 📜 Book of Abraham: Scripture/Book of Abraham.md
  - 💵 Tithing:
    - Tithing/Tithing.md
    - 🔎 Audits: Tithing/Tithing-Audits.md
    - 💸 Charitable Giving: Tithing/Charitable Giving.md
    - 🗣️ In General Conference: Tithing/In General Conference.md
    - 🧑‍⚖️ SEC: 
      - Tithing/SEC/SEC.md
      - 📃 SEC Order: Tithing/SEC/SEC Order.md
      - 🗣 WSJ Interview: Tithing/SEC/WSJ Interview.md
  - 🔗 Sources & More Material: Sources and Links.md

extra:
  analytics:
    provider: google
    property: G-WSB0F0E5MY
